language: node_js
sudo: required
dist: trusty
node_js:
  - v4
cache:
  directories:
    - node_modules
# whitelist
branches:
  only:
    - master
before_script:
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - npm i -g svgexport
  - npm i -g emoji-transmogrifier
script:
  - emoji-transmogrifier zap
  - gitbook install
  - gitbook build
  - gitbook pdf . build/DevBlog_Year1.pdf
  - gitbook mobi . build/DevBlog_Year1.mobi
  - gitbook epub . build/DevBlog_Year1.epub
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    rm -rf .git
    git config --global user.name "travis"
    git config --global user.email "travis"
    cd _book
    git init
    git remote add origin https://$GITHUB_API_KEY@github.com/edm00se/dev-blog-book
    git checkout -b gh-pages
    git fetch
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'Travis CI Deploying'
    git push -f origin gh-pages
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    cd ..
    cd build
    git init
    git remote add origin https://$GITHUB_API_KEY@github.com/edm00se/dev-blog-book
    git fetch
    git checkout -b built
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'Travis CI Deploying'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f origin built
    cd ..
  fi
