language: node_js
node_js:
  - v4
# whitelist
branches:
  only:
    - master
before_script:
  - sudo -v && wget -nvq -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - npm i -g svgexport
script:
  - gitbook install
  - gitbook build
  - gitbook pdf . build/DevBlog_Year1.pdf
  - gitbook mobi . build/DevBlog_Year1.mobi
  - gitbook epub . build/DevBlog_Year1.epub
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git config --global user.name "travis"
    git config --global user.email "travis"
    cd _book
    git init
    git remote add origin https://$GITHUB_API_KEY@github.com/user/repo
    git add .
    git commit -m 'Travis CI Deploying'
    git subtree push -q origin gh-pages
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    cd "$TRAVIS_BUILD_DIR"
    cd build
    git config --global user.name "travis"
    git config --global user.email "travis"
    cd _book
    git init
    git remote add origin https://$GITHUB_API_KEY@github.com/user/repo
    git add .
    git commit -m 'Travis CI Deploying'
    git subtree push -q origin built
    cd "$TRAVIS_BUILD_DIR"
  fi
