language: node_js
sudo: required
dist: trusty
node_js:
  - lts/*
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only: master
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq calibre libyajl-dev libxml2-dev libxqilla-dev
  - npm i -g gitbook-cli gitbook-plugin-youtube
script:
  - sudo chown -R $USER ~/
  - ./node_modules/emoji-transmogrifier/src/cli/index.js zap
  - gitbook fetch
  - gitbook init
  - gitbook build
  - gitbook pdf . build/DevBlog_Year1.pdf
  - gitbook mobi . build/DevBlog_Year1.mobi
  - gitbook epub . build/DevBlog_Year1.epub
after_success:
  - npm run deploy:travis
